### ISSUE TITLE
No attribute '_signature_version' with botocore v0.93

### ISSUE THREAD

**Issue by ballagas** [nanvel/tornado-botocore#4]
Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1320, in _stack_context_handle_exception
        raise_exc_info((type, value, traceback))
      File "/usr/local/lib/python2.7/dist-packages/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1512, in future_complete
        f.result()
      File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 227, in wrapper
        runner.run()
      File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 529, in run
        yielded = self.gen.throw(*exc_info)
      File "/home/kindoma/kindoma/awsAuthenticationHandler.py", line 43, in get
        Logins = logins
      File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 557, in run
        self.yield_point.start(self)
      File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 377, in start
        self.func(*self.args, **self.kwargs)
      File "/usr/local/lib/python2.7/dist-packages/tornado_botocore/base.py", line 81, in call
        return self.operation_call(endpoint=self.endpoint, callback=callback, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/tornado_botocore/base.py", line 32, in operation_call
        operation_model=self.operation.model, request_dict=request_dict)
      File "/usr/local/lib/python2.7/dist-packages/tornado_botocore/base.py", line 45, in make_request
        do_auth = self.endpoint._signature_version and self.endpoint.auth
    AttributeError: 'Endpoint' object has no attribute '_signature_version'

The exception goes away if I downgrade botocore to 0.76.0.  Did not test versions in between.

**Comment by nanvel** [comment]
I use version 0.65.0 successfully.
As You may see, tornado_botocore is just a dirty patch for botocore library, and it does not protected from issues like this.
If the version matters for You, try to fix tornado-botocore code or implement something similar for botocore version You want to use.

**Comment by ballagas** [comment]
Fair enough.  The README should be more explicit about botocore version support and your inclinations for future support.

**Comment by nanvel** [comment]
version 1.0.1 supports latest botocore==1.2.0.
